
services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - network1
      - backend

networks:
  network1:
    name: docker_default
    external: true
  backend:
    driver: bridge